config/routes.rb
Blogger::Application.routes.draw do
  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  
  def tag_list
    tags.join(", ")
  end
  
  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings
  
  def to_s
    name
  end
  
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  def index
    @articles = Article.all
  end
  
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    
    flash.notice = "Article '#{@article.title}' Updated!"
    
    redirect_to article_path(@article)
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.delete
    redirect_to articles_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    @comment.save

    redirect_to article_path(@comment.article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
  
  def index
    @tags = Tag.all
  end
  
  def destroy
    @tag = Tag.find(params[:id])
    @tag.delete
    redirect_to tags_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  
  def article_params
    params.require(:article).permit(:title, :body, :tag_list)
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article),
          class: 'article_title', id: "article_#{article.id}"%>
    </li>
  <% end %>
</ul>
  <%= link_to "Create a New Article", new_article_path,
      class: "new_article" %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
  <p>
    Tags:
    <% @article.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
    <% end %>
  </p>
<p><%= @article.body %></p>
<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>

<%= render partial: 'comments/form' %>

<%= link_to "<< Back to Articles List", articles_path %>
<%= link_to "delete", article_path(@article), method: :delete,
     data: {confirm: "Really delete the article?"}%>
<%= link_to "edit", edit_article_path(@article) %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your Name" %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Your Comment" %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="flash"><%= flash.notice %></p>

<%= yield %>

</body>
</html>

app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul id="tags">
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag),
          class: 'tag_name', id: "tag_#{tag.id}"%>
       <%= link_to "destroy", tag_path(tag), method: :delete%>
    </li>
  <% end %>
 

</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>